name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push backend
        run: |
          docker build . -f Dockerfile.backend -t ${{ secrets.ACR_LOGIN_SERVER }}/backend:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend:${{ github.sha }}

      - name: Deploy backend
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: Bibash_Check
          containerAppName: testing
          imageToDeploy: ${{ secrets.ACR_LOGIN_SERVER }}/backend:${{ github.sha }}